### ISSUE TITLE
Ember.computed.uniqBy is not exposed

### ISSUE THREAD

**Issue by kevinansfield** [ember-cli/ember-cli-shims#131]
The [computed property macros list](https://github.com/ember-cli/ember-cli-shims/blob/master/vendor/ember-cli-shims/app-shims.js#L203-L211) is missing the `uniqBy` macro resulting in errors such as `(0 , _emberComputed.uniqBy) is not a function` when trying to import it via `import {uniqBy} from 'ember-computed';`.

**Comment by Turbo87** [comment]
`uniqBy` is correctly exported by the New Module Imports (see https://github.com/ember-cli/ember-rfc176-data#emberobject), which should be used instead of `ember-cli-shims`. Since this project here is essentially frozen and deprecated I'm going to close this issue and referring you to the New Module Imports as a replacement.
